version: '3'
services:
  backend:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    depends_on:
      - frontend
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./citizen-database/my-app
    ports:
      - "3000:80"
    volumes:
      - ./citizen-database/my-app:/app
